dataset:
    name: nuscenes
    version: v1.0-mini
    path: /home/coisini/data/nuscenes
    sample_pkl_path: /home/coisini/data/nuscenes/nuscenes_pkl
    fcclip_feature_path: /home/coisini/data/nuscenes_fcclip_features
    rotate_aug: True
    flip_aug: True
    max_volume_space: [ 100, 3.1415926, 3 ]
    min_volume_space: [ 0, -3.1415926, -5 ]
    gt_generator:
        sigma: 5
    grid_size: [480,360,32]
    inst_aug:
        if_use: False
        aug_type: contmix
        inst_pkl_path: ../data/nuscenes/inst_database_train_info.pkl
        inst_trans: True # random translation for contmix
        inst_rotate: True
        inst_flip: True
        inst_add: True
    num_worker: 4
    min_points: 15
model:
    pix_fusion: True
    pix_fusion_path: ./checkpoints/resnet18-5c106cde.pth
    use_sara: True
    use_att: True
    model_load_path: null
    scatter_points_mode: 'mean'
    model_save_path: ./nusc_mini.pt
    train_batch_size: 1
    val_batch_size: 1
    learning_rate: 0.004
    LR_MILESTONES: [100, 150,200]
    IMAGE_SIZE: [900,1600]
    deconv_layers: 3
    pe_type: 'mpe'
    query_embed_dims: 256
    num_queries: 128
    deconv_hidden_dim: 64
    fcclip_vision_dim: 1536
    fcclip_text_dim: 768
    LR_GAMMA: 0.5
    check_iter: 162
    max_epoch: 300
    post_proc:
        threshold: 0.1
        nms_kernel: 5
        top_k: 100
    loss_mask:
            type: 'mmdet.FocalLoss'
            use_sigmoid: True
            gamma: 2.0
            alpha: 0.25
            reduction: 'mean'
            loss_weight: 1.0
    loss_dice:
        type: 'mmdet.DiceLoss'
        loss_weight: 2.0
    loss_cls:
        type: 'mmdet.FocalLoss'
        use_sigmoid: True
        gamma: 4.0
        alpha: 0.25
        loss_weight: 1.0
    center_loss: MSE
    offset_loss: L1
    center_loss_weight: 100
    offset_loss_weight: 10